services:
  go-server:
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    volumes:
      - ./go:/app
    env_file:
      - ./go/.env
    working_dir: /app

  node-server:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
    env_file:
      - ./node/.env
    working_dir: /app
